// js/models.js
const MODELS = [
  // ── GROQ ────────────────────────────────────────────────────────────────────
  // Change this entry in js/models.js:
  {
    id: "meta-llama/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout",
    provider: "groq",
    category: "Fast",
    description: "Meta's efficient Llama 4 – blazing fast with native tool use",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.11,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B",
    provider: "groq",
    category: "Balanced",
    description: "Versatile large language model by Meta via Groq",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.8,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Llama 3.1 8B",
    provider: "groq",
    category: "Fast",
    description: "Tiny and instant – great for simple tasks",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.2,
    badge: "🚀 Instant",
    badgeColor: "#3b82f6",
  },
  // ── NVIDIA ───────────────────────────────────────────────────────────────────
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1",
    name: "Nemotron 3 Super",
    provider: "nvidia",
    category: "Powerful",
    description: "NVIDIA's fine-tuned Nemotron with enhanced reasoning",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    name: "Nemotron Ultra 253B",
    provider: "nvidia",
    category: "Most Powerful",
    description: "NVIDIA's most powerful model – 253B parameters",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 5,
    badge: "🌟 Premium",
    badgeColor: "#f59e0b",
  },
  {
    id: "meta/llama-3.1-405b-instruct",
    name: "GPT-OSS 120B",
    provider: "nvidia",
    category: "Powerful",
    description: "Open-source frontier model hosted on NVIDIA NIM",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 3,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "groq",
    category: "Powerful",
    description: "OpenAI's flagship open-weight model with built-in reasoning",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 0.15,
    badge: "🧠 Deep Thinker",
    badgeColor: "#8b5cf6",
  },
  {
    id: "deepseek-ai/deepseek-r1",
    name: "DeepSeek R1",
    provider: "nvidia",
    category: "Reasoning",
    description: "DeepSeek's reasoning model – step-by-step thinking",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
  {
    id: "deepseek-ai/deepseek-v3-0324",
    name: "DeepSeek V4",
    provider: "nvidia",
    category: "Powerful",
    description: "DeepSeek's latest frontier model",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 2,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  // ── MISTRAL (LeChat) ─────────────────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    provider: "mistral",
    category: "Powerful",
    description: "Mistral's flagship model – powerful and accurate",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 2,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  {
    id: "codestral-latest",
    name: "Codestral",
    provider: "mistral",
    category: "Code",
    description: "Mistral's code-specialized model – best for programming",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 1,
    badge: "💻 Code",
    badgeColor: "#0ea5e9",
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small 4",
    provider: "mistral",
    category: "Fast",
    description: "Fast and efficient Mistral model for everyday use",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.5,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "magistral-medium-2506",
    name: "Magistral Medium",
    provider: "mistral",
    category: "Reasoning",
    description: "Mistral's reasoning-enhanced medium model",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2.5,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
  // ── GOOGLE ───────────────────────────────────────────────────────────────────
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    category: "Fast",
    description: "Google's fastest Gemini – great all-around model",
    hasReasoning: false,
    hasVision: true,
    costPerKTokens: 0.5,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "gemini-2.5-pro-preview-06-05",
    name: "Gemini 2.5 Pro",
    provider: "google",
    category: "Most Powerful",
    description: "Google's most capable Gemini with deep reasoning",
    hasReasoning: true,
    hasVision: true,
    costPerKTokens: 4,
    badge: "🌟 Premium",
    badgeColor: "#f59e0b",
  },
  {
    id: "gemini-2.0-flash-thinking-exp",
    name: "Gemini Flash Thinking",
    provider: "google",
    category: "Reasoning",
    description: "Flash with experimental thinking capabilities",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 1.5,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
];

const CATEGORIES = ["All", "Fast", "Balanced", "Powerful", "Most Powerful", "Reasoning", "Code"];

const PROVIDER_INFO = {
  groq:    { name: "Groq",         color: "#f97316", logo: "⚡" },
  nvidia:  { name: "NVIDIA",       color: "#76b900", logo: "🟢" },
  mistral: { name: "Mistral / LeChat", color: "#ff7000", logo: "🌊" },
  google:  { name: "Google AI",    color: "#4285f4", logo: "🔵" },
};

export { MODELS, CATEGORIES, PROVIDER_INFO };
