// js/models.js
const MODELS = [
  // ── GROQ ────────────────────────────────────────────────────────────────────
  {
    id: "meta-llama/llama-4-maverick-17b-128e-instruct",
    name: "Llama 4 Maverick",
    provider: "groq",
    category: "Fast",
    description: "Meta's latest Llama 4 – blazing fast with vision support",
    hasReasoning: false,
    hasVision: true,
    costPerKTokens: 0.5,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B",
    provider: "groq",
    category: "Balanced",
    description: "Versatile large language model by Meta via Groq",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.8,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Llama 3.1 8B",
    provider: "groq",
    category: "Fast",
    description: "Tiny and instant – great for simple tasks",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.2,
    badge: "🚀 Instant",
    badgeColor: "#3b82f6",
  },
  // ── NVIDIA ───────────────────────────────────────────────────────────────────
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1",
    name: "Nemotron 3 Super",
    provider: "nvidia",
    category: "Powerful",
    description: "NVIDIA's fine-tuned Nemotron with enhanced reasoning",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    name: "Nemotron Ultra 253B",
    provider: "nvidia",
    category: "Most Powerful",
    description: "NVIDIA's most powerful model – 253B parameters",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 5,
    badge: "🌟 Premium",
    badgeColor: "#f59e0b",
  },
  {
    id: "meta/llama-3.1-405b-instruct",
    name: "GPT-OSS 120B",
    provider: "nvidia",
    category: "Powerful",
    description: "Open-source frontier model hosted on NVIDIA NIM",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 3,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  {
    id: "meta/llama-3.2-3b-instruct",
    name: "GPT-OSS 20B",
    provider: "nvidia",
    category: "Balanced",
    description: "Efficient open-source model for everyday tasks",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 1,
    badge: "⚖️ Balanced",
    badgeColor: "#06b6d4",
  },
  // Fix DeepSeek R1 in js/models.js
  {
    id: "deepseek-ai/deepseek-r1-distill-llama-70b", // Changing this to the active, ultra-fast 70B production endpoint
    name: "DeepSeek R1",
    provider: "nvidia",
    category: "Reasoning",
    description: "DeepSeek's reasoning model – step-by-step thinking",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  },
  {
    id: "deepseek-ai/deepseek-v3", // NVIDIA uses 'deepseek-v3' as the production alias for the V-series
    name: "DeepSeek V4",
    provider: "nvidia",
    category: "Powerful",
    description: "DeepSeek's latest frontier model",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 2,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  // ── MISTRAL (LeChat) ─────────────────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    provider: "mistral",
    category: "Powerful",
    description: "Mistral's flagship model – powerful and accurate",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 2,
    badge: "💪 Powerful",
    badgeColor: "#ef4444",
  },
  {
    id: "codestral-latest",
    name: "Codestral",
    provider: "mistral",
    category: "Code",
    description: "Mistral's code-specialized model – best for programming",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 1,
    badge: "💻 Code",
    badgeColor: "#0ea5e9",
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small 4",
    provider: "mistral",
    category: "Fast",
    description: "Fast and efficient Mistral model for everyday use",
    hasReasoning: false,
    hasVision: false,
    costPerKTokens: 0.5,
    badge: "⚡ Fast",
    badgeColor: "#10b981",
  },
  {
    id: "magistral-medium-2506",
    name: "Magistral Medium",
    provider: "mistral",
    category: "Reasoning",
    description: "Mistral's reasoning-enhanced medium model",
    hasReasoning: true,
    hasVision: false,
    costPerKTokens: 2.5,
    badge: "🧠 Reasoning",
    badgeColor: "#8b5cf6",
  }
];

const CATEGORIES = ["All", "Fast", "Balanced", "Powerful", "Most Powerful", "Reasoning", "Code"];

const PROVIDER_INFO = {
  groq:    { name: "Groq",         color: "#f97316", logo: "⚡" },
  nvidia:  { name: "NVIDIA",       color: "#76b900", logo: "🟢" },
  mistral: { name: "Mistral / LeChat", color: "#ff7000", logo: "🌊" },
};

export { MODELS, CATEGORIES, PROVIDER_INFO };
